OsamZo/hi-hello-spring

src/main/java/spring/hi_hello_spring/test/command/application/controller/TestController.java, src/main/java/spring/hi_hello_spring/test/command/application/dto/TestCreateReqDTO.java, src/main/java/spring/hi_hello_spring/test/command/application/dto/TestUpdateReqDTO.java, src/main/java/spring/hi_hello_spring/test/command/application/service/TestService.java, src/main/java/spring/hi_hello_spring/test/command/domain/aggregate/entity/Test.java, src/main/java/spring/hi_hello_spring/test/command/domain/repository/TestRepository.java, src/main/java/spring/hi_hello_spring/test/command/infrastructure/repository/JpaTestRepository.java, src/main/java/spring/hi_hello_spring/test/query/controller/TestQueryController.java, src/main/java/spring/hi_hello_spring/test/query/dto/TestAllQueryDTO.java, src/main/java/spring/hi_hello_spring/test/query/dto/TestQueryDTO.java, src/main/java/spring/hi_hello_spring/test/query/mapper/TestMapper.java, src/main/java/spring/hi_hello_spring/test/query/service/TestQueryService.java, src/main/resources/mapper/test/TestMapper.xml
close #3 
<br>
<br>
- 프로젝트 확인용 테스트 로직 구현 작업
=> [FEAT] 프로젝트 확인용 테스트 로직 구현 작업

.github/workflows/deploy.yml
close #5 
<br>
<br>
-  actions 코드 수정
=> [REFACTOR] actions 코드 수정

src/main/java/spring/hi_hello_spring/test/command/application/controller/TestController.java
close #9 
<br>
<br>
- 깃허브 ac tions 테스트용 코드 변경
=> [TEST] 깃허브 ac tions 테스트용 코드 변경

.github/workflows/deploy.yml
close #11 
<br>
<br>
- 
<br>
-
=> [FEAT] actions 코드 수정

.github/workflows/deploy.yml
close #13 
<br>
<br>
- Github Actions 코드 수정
=> [REFACTOR] Github Actions 코드 수정

.github/workflows/deploy.yml
close #15 
<br>
<br>
- Github Actions 설정 변경 작업
=> [REFACTOR] Github Actions 설정 변경 작업

.github/workflows/deploy.yml
close #17 
<br>
<br>
- 깃허브 액션 테스트
=> [REFACTOR] 깃허브 액션 테스트

.github/workflows/deploy.yml
close #19 
<br>
<br>
- 
<br>
-
=> [TEST] 깃허브 액션 테스트

.github/workflows/deploy.yml, src/main/java/spring/hi_hello_spring/common/s3/FileUploadDTO.java
close #21 
<br>
<br>
- 
<br>
-
=> [TEST] Github Actions 테스트 작업

src/main/java/spring/hi_hello_spring/test/command/application/controller/TestController.java
=> [CHORE] 테스트용 코드 작성

build.gradle, src/main/java/spring/hi_hello_spring/security/SecurityConfig.java
Security 기본 설정 작업 <br>
close #25 
<br>
<br>
- Security 기본 설정 작업
<br>
-
=> [FEAT] Security 기본 설정 작업

src/main/resources/hihellodb.sql
=> [FEAT] DDL 생성

src/main/resources/application.yml
ddl-auto none으로 변경
close #30
- ddl-auto none으로 변경
=> [REFACTOR] ddl-auto none으로 변경

src/main/resources/hihellodb.sql
DDL 리팩토링
close #33
- 챗봇 카테고리 테이블 추가
- 챗봇 테이블 외래키 설정(챗봇 카테고리)
- 템플릿 테이블 외래키 설정 (퀴즈 카테고리)
=> [REFACTOR] DDL 리팩토링

src/main/resources/data.sql, src/main/resources/hihellodb.sql
close #35 
<br>
<br>
- data sql 데이터 추가 작업
<br>
- ddl 구문 일부 수정
=> [FEAT] data sql 데이터 추가 작업

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/dto/MenteeAllQueryDTO.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml
멘티 그룹 매칭을 위한 멘티 전체 조회
close #44 
<br>
<br>
- 멘티 전체 조회
<br>
-
=> [FEAT] 멘티 전체 조회

src/main/java/spring/hi_hello_spring/common/aggregate/entity/EmployeeRole.java, src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Employee.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java, src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java, src/main/java/spring/hi_hello_spring/security/util/CustomUserDetailsService.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Employee Entity 수정
<br>
close #48 
<br>
<br>
- EmployeeRole 필드 값 String -> Enum 변경
<br>
- 로그인 시 헤더에 담는 토큰 key 네이밍 변경
=> [CHORE] Employee Entity 필드 수정

src/main/resources/hihellodb.sql
close #52 
<br>
<br>
-  DDL 구문 변경 작업
=> [REFACTOR] DDL 구문 변경 작업

src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java, src/main/resources/application.yml
secretkey 수정 및 토큰 만료 시간 수정
<br>
close #54 
<br>
<br>
- secretkey 수정 및 토큰 만료 시간 수정
<br>
-
=> [CHORE] secretkey 수정 및 토큰 만료 시간 수정

src/main/java/spring/hi_hello_spring/group/command/application/controller/PeerReviewListController.java, src/main/java/spring/hi_hello_spring/group/command/application/dto/PeerReviewListCreateDTO.java, src/main/java/spring/hi_hello_spring/group/command/application/service/PeerReviewListService.java, src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/PeerReviewList.java, src/main/java/spring/hi_hello_spring/group/command/domain/repository/PeerReviewListRepository.java, src/main/java/spring/hi_hello_spring/group/command/infrastructure/repository/JpaPeerReviewListRepository.java
close #{이슈넘버}
<br>
<br>
- 동료 평가 지표 등록 기능 구현
=> [FEAT] 동료 평가 지표 등록 기능 구현

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/dto/MenteeDepQueryDTO.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml
부서별 멘티 조회 기능
close #56
<br>
<br>
- 부서별 멘티 조회 기능
<br>
-
=> [FEAT] 부서별 멘티 조회 기능

src/main/java/spring/hi_hello_spring/group/command/application/controller/PeerReviewListController.java, src/main/java/spring/hi_hello_spring/group/command/application/service/PeerReviewListService.java, src/main/java/spring/hi_hello_spring/group/command/domain/repository/PeerReviewListRepository.java
close #60 
<br>
<br>
- 동료 평가 지표 삭제 기능 구현
=> [FEAT] 동료 평가 지표 삭제 기능 구현

src/main/java/spring/hi_hello_spring/group/query/controller/PeerReviewListQueryController.java, src/main/java/spring/hi_hello_spring/group/query/dto/PeerReviewListAllQueryDTO.java, src/main/java/spring/hi_hello_spring/group/query/mapper/PeerReviewListMapper.java, src/main/java/spring/hi_hello_spring/group/query/service/PeerReviewListQueryService.java, src/main/resources/data.sql, src/main/resources/mapper/group/PeerReviewListMapper.xml
close #63 
<br>
<br>
- 동료 평가 지표 리스트 조회 기능 구현
=> [FEAT] 동료 평가 지표 리스트 조회 기능 구현

src/main/resources/data.sql, src/main/resources/hihellodb.sql
close #66 
<br>
<br>
- ddl 구문 data 구문 변경 작업
=> [REFACTOR] ddl 구문 data 구문 변경 작업

src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java, src/main/java/spring/hi_hello_spring/security/repository/SecurityRepository.java, src/main/java/spring/hi_hello_spring/security/util/CustomUserDetailsService.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
SecurityRepository, EmployeeRepository 분리
<br>
close #68 
<br>
<br>
- SecurityRepository, EmployeeRepository 분리
<br>
-
=> [CHORE] SecurityRepository, EmployeeRepository 분리

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/EvalIndController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/EvalIndCreateDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/EvalIndService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/EvalInd.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalIndRepository.java, src/main/java/spring/hi_hello_spring/evaluation/command/infrastructure/JpaEvalIndRepository.java
close #67 
<br>
<br>
- 평가 지표 등록 기능 구현
=> [FEAT] 평가 지표 등록 기능 구현

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/EvalIndController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/EvalIndService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalIndRepository.java
close #76 
<br>
<br>
- 평가 지표 삭제 기능 구현
=> [FEAT] 평가 지표 삭제 기능 구현

.github/workflows/deploy.yml
close #80 
<br>
<br>
- Actions 코드 변경
=> [REFACTOR] Actions 코드 변경

src/main/java/spring/hi_hello_spring/evaluation/query/controller/EvalIndQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/EvalIndAllQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/EvalIndMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/EvalIndQueryService.java, src/main/resources/mapper/evaluation/evalind/EvalIndMapper.xml
close #78 
<br>
<br>
- 평가 지표 조회 기능 구현
=> [FEAT] 평가 지표 조회 기능 구현

src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizCategoryController.java, src/main/java/spring/hi_hello_spring/quiz/command/application/dto/QuizCategoryCreateDTO.java, src/main/java/spring/hi_hello_spring/quiz/command/application/service/QuizCategoryService.java, src/main/java/spring/hi_hello_spring/quiz/command/domain/aggregate/entity/QuizCategory.java, src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizCategoryRepository.java, src/main/java/spring/hi_hello_spring/quiz/command/infrastructure/repository/JpaQuizCategoryRepository.java
close #82 
<br>
<br>
- 퀴즈 카테고리 등록 기능 구현
=> [FEAT] 퀴즈 카테고리 등록 기능 구현 

src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizCategoryController.java, src/main/java/spring/hi_hello_spring/quiz/command/application/service/QuizCategoryService.java, src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizCategoryRepository.java
close #84 
<br>
<br>
- 퀴즈 카테고리 삭제 기능 구현
=> [FEAT] 퀴즈 카테고리 삭제 기능 구현

src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizCategoryController.java, src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizController.java, src/main/java/spring/hi_hello_spring/quiz/command/application/dto/QuizCreateDTO.java, src/main/java/spring/hi_hello_spring/quiz/command/application/service/QuizService.java, src/main/java/spring/hi_hello_spring/quiz/command/domain/aggregate/entity/Quiz.java, src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizCategoryRepository.java, src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizRepository.java, src/main/java/spring/hi_hello_spring/quiz/command/infrastructure/repository/JpaQuizRepository.java, src/main/java/spring/hi_hello_spring/quiz/query/controller/QuizCategoryQueryController.java
close #88
<br>
<br>
- 카테고리 별 퀴즈 추가 기능 구현
<br>
- 퀴즈 카테고리 엔드포인트
=> [FEAT] 카테고리 별 퀴즈 추가 기능 구현

src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizController.java, src/main/java/spring/hi_hello_spring/quiz/command/application/dto/QuizUpdateDTO.java, src/main/java/spring/hi_hello_spring/quiz/command/application/service/QuizService.java, src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizRepository.java
close #90 
<br>
<br>
- 카테고리 별 퀴즈 수정 기능 구현
=> [FEAT] 카테고리 별 퀴즈 수정 기능 구현

src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizController.java, src/main/java/spring/hi_hello_spring/quiz/command/application/service/QuizService.java, src/main/java/spring/hi_hello_spring/quiz/command/domain/repository/QuizRepository.java
close #92 
<br>
<br>
- 카테고리 별 퀴즈 삭제 기능 구현
=> [FEAT] 카테고리 별 퀴즈 삭제 기능 구현

src/main/java/spring/hi_hello_spring/group/command/application/controller/GroupMatchController.java, src/main/java/spring/hi_hello_spring/group/command/application/dto/MemberDTO.java, src/main/java/spring/hi_hello_spring/group/command/application/dto/TaskRequestDTO.java, src/main/java/spring/hi_hello_spring/group/command/application/dto/TaskRequestWrapper.java, src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java, src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/GroupMember.java, src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java, src/main/java/spring/hi_hello_spring/group/command/domain/repository/GroupMemberRepository.java, src/main/java/spring/hi_hello_spring/group/command/domain/repository/TaskGroupRepository.java
멘티 그룹핑 구현
close #46 
<br>
<br>
- 멘티 그룹핑 구현
<br>
-
=> [FEAT] 멘티 그룹핑 구현

src/main/java/spring/hi_hello_spring/wiki/command/application/controller/WikiController.java, src/main/java/spring/hi_hello_spring/wiki/command/application/dto/WikiCreateRequestDTO.java, src/main/java/spring/hi_hello_spring/wiki/command/application/service/WikiService.java, src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/Wiki.java, src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/WikiModContent.java, src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/WikiSnapshot.java, src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiModContentRepository.java, src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiRepository.java, src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiSnapshotRepository.java, src/main/java/spring/hi_hello_spring/wiki/command/infrastructure/repository/JpaWikiModContentRepository.java, src/main/java/spring/hi_hello_spring/wiki/command/infrastructure/repository/JpaWikiRepository.java, src/main/java/spring/hi_hello_spring/wiki/command/infrastructure/repository/JpaWikiSnapshotRepository.java
위키 등록 기능 구현
close #49
- 위키 등록 기능 구현
=> [FEAT] 위키 등록 기능 구현

src/main/java/spring/hi_hello_spring/group/command/application/controller/GroupMatchController.java, src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java, src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringMatchController.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/dto/MentoringGroupDTO.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringMatchService.java, src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Mentoring.java, src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/MentoringRepository.java
close #46 
<br>
- 멘토-멘티 그룹핑 구현
<br>
-
=> [FEAT] 멘토-멘티 그룹핑 구현

src/main/java/spring/hi_hello_spring/quiz/query/controller/QuizQueryController.java, src/main/java/spring/hi_hello_spring/quiz/query/dto/QuizAllQueryDTO.java, src/main/java/spring/hi_hello_spring/quiz/query/mapper/QuizMapper.java, src/main/java/spring/hi_hello_spring/quiz/query/service/QuizQueryService.java, src/main/resources/mapper/quiz/QuizMapper.xml
close #95 
<br>
<br>
- 카테고리 별 퀴즈 전체 조회 기능 구현
=> [FEAT] 카테고리 별 퀴즈 전체 조회 기능 구현

src/main/resources/data.sql, src/main/resources/hihellodb.sql
close #108 
<br>
<br>
- ddl, data 구문 변경 작업
=> [REFACTOR] ddl, data 구문 변경 작업

src/main/java/spring/hi_hello_spring/common/util/RedisService.java, src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
로그아웃 기능 구현
<br>
close #113
<br>
<br>
- 로그아웃 기능 구현
- 부당한 리프레시 토큰 요청 시 로그아웃 하도록 구현
<br>
- 메서드 명 수정
=> [FEAT] 로그아웃 기능 구현

src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
순환 의존성 오류 해결
<br>
close #125 
<br>
<br>
- 순환 의존성 오류 해결
<br>
-
=> [FIX] 순환 의존성 오류 해결

src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java, src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java, src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java, src/main/java/spring/hi_hello_spring/security/service/CustomUserDetailsService.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
요청 시 JwtFilter에서 걸리는 문제 해결
<br>
close #127 
<br>
<br>
- 요청 시 JwtFilter에서 걸리는 문제 해결
<br>
- 로그아웃 시 토큰 디코딩 오류 해결
=> [FIX] 요청 시 JwtFilter에서 걸리는 문제 해결

src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/TemplateController.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/dto/TeamplateOrderUpdateDTO.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/service/TemplateService.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/TemplateRepository.java
close #134 
<br>
<br>
- 온보딩 스토리 보드 순서 수정 기능 구현
=> [FEAT] 온보딩 스토리 보드 순서 수정 기능 구현

src/main/java/spring/hi_hello_spring/onboarding/query/controller/TemplateQueryController.java, src/main/java/spring/hi_hello_spring/onboarding/query/dto/TemplateAllQueryDTO.java, src/main/java/spring/hi_hello_spring/onboarding/query/mapper/TemplateMapper.java, src/main/java/spring/hi_hello_spring/onboarding/query/service/TemplateQueryService.java, src/main/resources/mapper/onboarding/TemplateMapper.xml
close #136 
<br>
<br>
- 온보딩 스토리보드 순서 전체 조회 기능 구현
=> [FEAT] 온보딩 스토리보드 순서 전체 조회 기능 구현

src/main/java/spring/hi_hello_spring/quiz/query/controller/QuizResultQueryController.java, src/main/java/spring/hi_hello_spring/quiz/query/dto/QuizResultAllQueryDTO.java, src/main/java/spring/hi_hello_spring/quiz/query/mapper/QuizResultMapper.java, src/main/java/spring/hi_hello_spring/quiz/query/service/QuizResultQueryService.java, src/main/resources/data.sql, src/main/resources/mapper/quiz/QuizResultMapper.xml
close #138 
<br>
<br>
- 카테고리 별 퀴즈 결과 전체 조회 기능 구현
=> [FEAT] 카테고리 별 퀴즈 결과 전체 조회 기능 구현

src/main/java/spring/hi_hello_spring/wiki/query/controller/WikiQueryController.java, src/main/java/spring/hi_hello_spring/wiki/query/dto/WikiHistoryListQueryDTO.java, src/main/java/spring/hi_hello_spring/wiki/query/mapper/WikiMapper.java, src/main/java/spring/hi_hello_spring/wiki/query/service/WikiQueryService.java, src/main/resources/mapper/wiki/WikiMapper.xml
위키 히스토리 리스트 조회 기능 구현
close #141
-  위키 히스토리 리스트 조회 기능 구현
=> [FEAT] 위키 히스토리 리스트 조회 기능 구현

src/main/java/spring/hi_hello_spring/wiki/command/application/controller/WikiController.java, src/main/java/spring/hi_hello_spring/wiki/command/application/service/WikiService.java, src/main/java/spring/hi_hello_spring/wiki/command/domain/aggregate/entity/Wiki.java, src/main/java/spring/hi_hello_spring/wiki/command/domain/repository/WikiRepository.java
위키 삭제 기능 구현
close #132
- 위키 삭제 기능 구현
=> [FEAT] 위키 삭제 기능 구현

src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/GroupTaskAllQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskQueryMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java, src/main/resources/mapper/evaluation/task/TaskMapper.xml
close #140 
<br>
<br>
- 그룹 과제 제목 리스트 조회 기능 구현
=> [FEAT] 그룹 과제 제목 리스트 조회 기능 구현

src/main/java/spring/hi_hello_spring/group/query/controller/TaskGroupQueryController.java, src/main/java/spring/hi_hello_spring/group/query/dto/TaskGroupListQueryDTO.java, src/main/java/spring/hi_hello_spring/group/query/mapper/TaskGroupMapper.java, src/main/java/spring/hi_hello_spring/group/query/service/TaskGroupQueryService.java, src/main/resources/mapper/group/TaskGroupMapper.xml
close #148 
<br>
<br>
- 그룹 과제 별 그룹 리스트 조회 기능 구현
=> [FEAT] 그룹 과제 별 그룹 리스트 조회 기능 구현

.github/workflows/deploy.yml
close #152 
<br>
<br>
- github actions 코드 변경
=> [REFACTOR] github actions 코드 변경

src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/EvalList.java, src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/EvalListQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMenteeDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMentorDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskQueryMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java, src/main/resources/data.sql, src/main/resources/hihellodb.sql, src/main/resources/mapper/evaluation/task/TaskMapper.xml
(멘토) 멘티 과제 상세조회 기능 구현
<br>
close #120 
<br>
<br>
- 
<br>
-
=> [FEAT] (멘토) 멘티 과제 상세조회 기능 구현

src/main/java/spring/hi_hello_spring/group/query/controller/PeerReviewResultQueryController.java, src/main/java/spring/hi_hello_spring/group/query/dto/PeerReviewResultAllQueryDTO.java, src/main/java/spring/hi_hello_spring/group/query/mapper/PeerReviewResultMapper.java, src/main/java/spring/hi_hello_spring/group/query/service/PeerReviewResultQueryService.java, src/main/resources/mapper/group/PeerReviewResultMapper.xml
close #150 
<br>
<br>
- 동료 평가 결과 리스트 조회
=> [FEAT] 동료 평가 결과 리스트 조회

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/EvalListController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/EvalListCreateDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/EvalListService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/EvalList.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalIndRepository.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalListRepository.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskRepository.java, src/main/java/spring/hi_hello_spring/evaluation/command/infrastructure/JpaEvalListRepository.java, src/main/java/spring/hi_hello_spring/evaluation/command/infrastructure/JpaTaskRepository.java
과제 평가 항목 등록 기능 구현
close #146
- 과제 평가 항목 등록 기능 구현
=> [FEAT] 과제 평가 항목 등록 기능 구현

src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java, src/main/java/spring/hi_hello_spring/employee/command/application/controller/HRController.java, src/main/java/spring/hi_hello_spring/employee/command/application/dto/HR/CreateEmplReqDTO.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java, src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Department.java, src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Employee.java, src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Position.java, src/main/java/spring/hi_hello_spring/employee/command/domain/repository/DepartmentRepository.java, src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java, src/main/java/spring/hi_hello_spring/employee/command/domain/repository/PositionRepository.java, src/main/java/spring/hi_hello_spring/employee/command/infrastructure/repository/JpaDepartmentRepository.java, src/main/java/spring/hi_hello_spring/employee/command/infrastructure/repository/JpaEmployeeRepository.java, src/main/java/spring/hi_hello_spring/employee/command/infrastructure/repository/JpaPositionRepository.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
(담당자) 사원 등록 기능 구현
<br>
close #151 
<br>
<br>
- (담당자) 사원 등록 기능 구현
<br>
- 사원 스웨거 Tag 수정
- jwtutil 에서 특정 Bean을 찾지 못하는 현상 해결
=> [FEAT] (담당자) 사원 등록 기능 구현

src/main/java/spring/hi_hello_spring/common/exception/ErrorCodeType.java, src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java, src/main/java/spring/hi_hello_spring/employee/command/application/controller/HRController.java, src/main/java/spring/hi_hello_spring/employee/command/application/dto/employee/ModifyPasswordReqDTO.java, src/main/java/spring/hi_hello_spring/employee/command/application/dto/hr/CreateEmplReqDTO.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java, src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Employee.java, src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
사원 비밀번호 변경 기능 구현
<br>
close #162 
<br>
<br>
- 사원 비밀번호 변경 기능 구현 
<br>
- 구조 수정
- jwtfilter 불필요 코드 및 주석 제거
=> [FEAT] 사원 비밀번호 변경 기능 구현 

src/main/java/spring/hi_hello_spring/employee/command/application/controller/HRController.java, src/main/java/spring/hi_hello_spring/employee/command/application/dto/hr/ModifyEmplReqDTO.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java, src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Employee.java
사원 수정 기능 구현
<br>
close #164 
<br>
<br>
- 사원 수정 기능 구현
<br>
-
=> [FEAT] 사원 수정 기능 구현

src/main/java/spring/hi_hello_spring/employee/command/application/controller/HRController.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java, src/main/java/spring/hi_hello_spring/employee/command/domain/aggregate/entity/Employee.java, src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java
사원 삭제 기능 구현
<br>
close #167 
<br>
<br>
- 사원 삭제 기능 구현
<br>
-
=> [FEAT] 사원 삭제 기능 구현

src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/ReportController.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/dto/WriteReportDTO.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/ReportService.java, src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Report.java, src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/MentoringRepository.java, src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/ReportRepository.java
(멘티) 보고서 내용 작성 기능 구현
<br>
close #183 
<br>
<br>
- (멘티) 보고서 내용 작성 기능 구현
<br>
-
=> [FEAT] (멘티) 보고서 내용 작성 기능 구현

src/main/java/spring/hi_hello_spring/finalEval/query/controller/FinalEvalQueryController.java, src/main/java/spring/hi_hello_spring/finalEval/query/dto/FinalEvalsQueryDTO.java, src/main/java/spring/hi_hello_spring/finalEval/query/mapper/FinalEvalMapper.java, src/main/java/spring/hi_hello_spring/finalEval/query/service/FinalEvalQueryService.java, src/main/resources/mapper/finalEval/FinalEvalMapper.xml
최종평가 목록 조회 기능 구현
close #181
- 최종평가 목록 조회 기능 구현
=> [FEAT] 최종평가 목록 조회 기능 구현

src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/ReportController.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/ReportService.java, src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/ReportRepository.java
(멘티) 보고서 내용 수정 기능 구현
<br>
close #186 
<br>
<br>
- (멘티) 보고서 내용 수정 기능 구현
<br>
-
=> [FEAT] (멘티) 보고서 내용 수정 기능 구현

src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/PeerReview.java, src/main/java/spring/hi_hello_spring/group/query/controller/PeerReviewResultQueryController.java, src/main/java/spring/hi_hello_spring/group/query/dto/PeerReviewDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/group/query/dto/PeerReviewResultDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/group/query/mapper/PeerReviewResultMapper.java, src/main/java/spring/hi_hello_spring/group/query/service/PeerReviewResultQueryService.java, src/main/resources/application.yml, src/main/resources/mapper/group/PeerReviewResultMapper.xml
close #160 
<br>
<br>
- 동료 평가 결과 상세 조회 기능 구현
=> [FEAT] 동료 평가 결과 상세 조회 기능 구현

src/main/java/spring/hi_hello_spring/common/repository/FileRepository.java, src/main/java/spring/hi_hello_spring/common/s3/FileUploadUtil.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringPlanController.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringPlanService.java
close #179 
<br>
-  멘토링 계획서 삭제
<br>
-
=> [FEAT] 멘토링 계획서 삭제

src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringPlanController.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/dto/MentoringPlanUpdateDTO.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringPlanService.java
close #180 
<br>
- 멘토링 계획서 처리
<br>
-
=> [FEAT] 멘토링 계획서 처리

src/main/java/spring/hi_hello_spring/finalEval/query/controller/FinalEvalQueryController.java, src/main/java/spring/hi_hello_spring/finalEval/query/dto/FinalEvalDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/finalEval/query/mapper/FinalEvalMapper.java, src/main/java/spring/hi_hello_spring/finalEval/query/service/FinalEvalQueryService.java, src/main/resources/mapper/finalEval/FinalEvalMapper.xml
최종평가 상세조회 기능 구현
close #147
- 최종평가 상세조회 기능 구현
<br>
=> [FEAT] 최종평가 상세조회 기능 구현

src/main/resources/hihellodb.sql
DDL 수정
close #195
- 과제, 템플릿 간 연관관계 추가
=> [REFACTOR] DDL 수정

src/main/java/spring/hi_hello_spring/mentoring/query/controller/MentoringQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/MentoringPlanListAllQueryDTO.java, src/main/java/spring/hi_hello_spring/mentoring/query/mapper/MentoringPlanMapper.java, src/main/java/spring/hi_hello_spring/mentoring/query/service/MentoringPlanningQueryService.java, src/main/resources/mapper/mentoring/MentoringPlanningMapper.xml
close #176 
<br>
- 멘토링 계획서 전체 리스트 조회
<br>
-
=> [FEAT] 멘토링 계획서 전체 리스트 조회

src/main/java/spring/hi_hello_spring/mentoring/query/controller/MentoringQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/MentoringPlanDetailDTO.java, src/main/java/spring/hi_hello_spring/mentoring/query/mapper/MentoringPlanMapper.java, src/main/java/spring/hi_hello_spring/mentoring/query/service/MentoringPlanningQueryService.java, src/main/resources/mapper/mentoring/MentoringPlanningMapper.xml
close #177 
<br>
<br>
- 멘토링 계획서 상세 조회
<br>
-
=> [FEAT] 멘토링 계획서 상세 조회

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/dto/ReqEmplInfoQueryDTO.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/ReportController.java, src/main/java/spring/hi_hello_spring/mentoring/command/domain/aggregate/entity/Mentoring.java, src/main/resources/mapper/employee/EmployeeMapper.xml
사원 내 프로필 조회 기능 구현
<br>
close #199 
<br>
<br>
- 사원 내 프로필 조회 기능 구현
<br>
- 레포트 컨트롤러 엔드포인트 수정
- 멘토링 Entity 필드 추가
=> [FEAT] 사원 내 프로필 조회 기능 구현

src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/ReportService.java
service 계층 Transactional 추가
<br>
close #201 
<br>
<br>
- service 계층 Transactional 추가
<br>
-
=> [CHORE] service 계층 Transactional 추가

src/main/resources/data.sql, src/main/resources/hihellodb.sql
DDL 수정
멘토링 테이블에 멘토링 진행 현황 컬럼 추가
close #203 
<br>
<br>
- 멘토링 테이블에 멘토링 진행 현황 컬럼 추가
<br>
-
=> [CHORE] 멘토링 테이블에 멘토링 진행 현황 컬럼 추가

src/main/java/spring/hi_hello_spring/mentoring/query/controller/MentoringQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/MentoringPlanSearchDTO.java, src/main/java/spring/hi_hello_spring/mentoring/query/mapper/MentoringPlanMapper.java, src/main/java/spring/hi_hello_spring/mentoring/query/service/MentoringPlanningQueryService.java, src/main/resources/mapper/mentoring/MentoringPlanningMapper.xml
close #178
<br>
- 멘토링 계획서 검색(name, title)
<br>
-
=> [FEAT] 멘토링 계획서 검색(name, title)

src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/Task.java, src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java, src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java, src/main/java/spring/hi_hello_spring/group/query/service/TaskGroupQueryService.java
DDL 수정에 따른 리팩토링
close #206
- task_group_num 컬럼 생성에 따른 리팩토링
- task와 template 연관관계 생성에 따른 리팩토링
=> [REFACTOR] DDL 수정에 따른 리팩토링

src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskEvalQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskEvalListQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskEvalMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskEvalQueryService.java, src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml
과제 평가 리스트 조회 기능 구현
close #147
- 과제 평가 리스트 조회 기능 구현
=> [FEAT] 과제 평가 리스트 조회 기능 구현

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
(멘티) 멘토 프로필 조회 기능 구현
<br>
close #209
<br>
<br>
- (멘티) 멘토 프로필 조회 기능 구현
<br>
-
=> [FEAT] (멘티) 멘토 프로필 조회 기능 구현

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
멘토/멘티 프로필 조회 기능 통합 구현
<br>
close #211 
<br>
<br>
- 멘토/멘티 프로필 조회 기능 통합 구현
<br>
-
=> [CHORE] 멘토/멘티 프로필 조회 기능 통합 구현

src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml
그룹 과제 평가 리스트 조회 문제 해결
close #213
- 그룹 과제 평가 리스트 조회 문제 해결
=> [FIX] 그룹 과제 평가 리스트 조회 문제 해결

src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskEvalQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskEvalDetailsQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskEvalMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskEvalQueryService.java, src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml
과제 평가 상세조회 기능 구현
close #157
- 과제 평가 상세조회 기능 구현
=> [FEAT] 과제 평가 상세조회 기능 구현

src/main/java/spring/hi_hello_spring/employee/query/dto/ReqEmplInfoQueryDTO.java, src/main/resources/mapper/employee/EmployeeMapper.xml
프로필 조회 프로필 사진까지 조회 되도록 수정
<br>
close #216 
<br>
<br>
- 프로필 조회 프로필 사진까지 조회되도록 수정
<br>
-
=> [CHORE] 프로필 조회 프로필 사진까지 조회되도록 수정

src/main/resources/data.sql
data.sql 수정
close #225
- data.sql 수정
<br>
-
=> [REFACTOR] data.sql 수정

src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/ResMentoringReportDTO.java, src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java, src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java, src/main/resources/data.sql, src/main/resources/mapper/mentoring/ReportMapper.xml
멘토링 보고서 상세 조회 기능 구현
<br>
close #220 
<br>
<br>
- 멘토링 보고서 상세 조회 기능 구현
<br>
- 멘토링 보고서 데이터 추가
=> [FEAT] 멘토링 보고서 상세 조회 기능 구현

src/main/resources/data.sql
close #232 
<br>
<br>
- data sql 데이터 추가 (퀴즈)
=> [FEAT] data sql 데이터 추가 (퀴즈)

src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/ReportController.java, src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/ReportListQueryDTO.java, src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java, src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java, src/main/resources/mapper/mentoring/ReportMapper.xml
(담당자) 멘토링 보고서 리스트 조회 기능 구현
<br>
close #228 
<br>
<br>
- (담당자) 멘토링 보고서 리스트 조회 기능 구현
<br>
-
=> [FEAT] (담당자) 멘토링 보고서 리스트 조회 기능 구현

src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java, src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java, src/main/resources/data.sql, src/main/resources/mapper/mentoring/ReportMapper.xml
(팀장) 멘토링 보고서 리스트 조회 기능 구현
close #229 
<br>
<br>
- (팀장) 멘토링 보고서 리스트 조회 기능 구현
<br>
- 데이터 추가
=> [FEAT] (팀장) 멘토링 보고서 리스트 조회 기능 구현

src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java, src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java, src/main/resources/mapper/mentoring/ReportMapper.xml
(멘토) 멘토링 보고서 리스트 조회 기능 구현
<br>
close #230 
<br>
<br>
- (멘토) 멘토링 보고서 리스트 조회 기능 구현
<br>
-
=> [FEAT] (멘토) 멘토링 보고서 리스트 조회 기능 구현

src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/MenteeReportListQueryDTO.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/ReportListQueryDTO.java, src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java, src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java, src/main/resources/mapper/mentoring/ReportMapper.xml
(멘티) 멘토링 보고서 리스트 조회 기능 구현
close #{이슈넘버}
<br>
<br>
- (멘티) 멘토링 보고서 리스트 조회 기능 구현
<br>
- 보고서 리스트 조회 DTO 수정
=> [FEAT] (멘티) 멘토링 보고서 리스트 조회 기능 구현

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/dto/EmployeeListDTO.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml
사원 리스트 조회 기능 구현
<br>
close #238 
<br>
<br>
- 사원 리스트 조회 기능 구현
<br>
-
=> [FEAT] 사원 리스트 조회 기능 구현

src/main/java/spring/hi_hello_spring/employee/query/dto/ReqEmplInfoQueryDTO.java, src/main/resources/mapper/employee/EmployeeMapper.xml
프로필 조회 DTO 추가 및 쿼리문 수정
<br>
close #241 
<br>
<br>
- 프로필 조회 DTO 추가 및 쿼리문 수정
<br>
-
=> [CHORE] 프로필 조회 DTO 추가 및 쿼리문 수정

src/main/java/spring/hi_hello_spring/HiHelloSpringApplication.java, src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java, src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatRoomController.java, src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRequestMessage.java, src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRoom.java, src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatRoomService.java, src/main/java/spring/hi_hello_spring/chatting/command/domain/aggregate/ChatMessage.java, src/main/java/spring/hi_hello_spring/chatting/command/domain/repository/mongo/ChatMessageMongoRepository.java, src/main/java/spring/hi_hello_spring/chatting/query/controller/ChattingQueryController.java, src/main/java/spring/hi_hello_spring/chatting/query/dto/ChattingRoomList.java, src/main/java/spring/hi_hello_spring/chatting/query/mapper/ChattingMapper.java, src/main/java/spring/hi_hello_spring/chatting/query/service/ChattingQueryService.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringMatchService.java, src/main/resources/mapper/chatting/ChattingListMapper.xml
close #240 
<br>
<br>
-  멘토링 채팅방 조회
<br>
-
=> [FEAT] 멘토링 채팅방 조회

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml
사원 검색 기능 구현
<br>
close #244 
<br>
<br>
- 사원 검색 기능 구현
<br>
-
=> [FEAT] 사원 검색 기능 구현

src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatRoomController.java, src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRoom.java, src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatRoomService.java, src/main/java/spring/hi_hello_spring/chatting/query/controller/ChattingQueryController.java, src/main/java/spring/hi_hello_spring/chatting/query/mapper/ChattingMapper.java, src/main/java/spring/hi_hello_spring/chatting/query/service/ChattingQueryService.java, src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java, src/main/java/spring/hi_hello_spring/group/command/domain/repository/GroupMemberRepository.java, src/main/java/spring/hi_hello_spring/group/command/domain/repository/TaskGroupRepository.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringMatchService.java, src/main/resources/mapper/chatting/ChattingListMapper.xml
close #245 
close #246
<br>
- 그룹핑 방 생성, 본인이 들어간 채팅 방 조회
<br>
-
=> [FEAT]  그룹핑 방 생성, 조회

src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java, src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java, src/main/resources/mapper/mentoring/ReportMapper.xml
(담당자, 팀장) 멘토링 보고서 검색 기능 구현
<br>
close #248 
<br>
<br>
-  (담당자, 팀장) 멘토링 보고서 검색 기능 구현
<br>
-
=> [FEAT] (담당자, 팀장) 멘토링 보고서 검색 기능 구현

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml
사원 이름 조회 기능 구현
<br>
close #256 
<br>
<br>
- 사원 이름 조회 기능 구현
<br>
-
=> [FEAT] 사원 이름 조회 기능 구현

src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
close #258 
<br>
<br>
- CORS 설정 작업
=> [FEAT] CORS 설정 작업

docker-compose.yml, src/main/java/spring/hi_hello_spring/chatting/WebSocketConfig.java, src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java, src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRequestMessage.java, src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatMessageListener.java, src/main/java/spring/hi_hello_spring/chatting/command/domain/aggregate/ChatMessage.java, src/main/java/spring/hi_hello_spring/config/KafkaConfig.java, src/main/java/spring/hi_hello_spring/config/ListenerConfiguration.java, src/main/java/spring/hi_hello_spring/config/MongoConfig.java, src/main/java/spring/hi_hello_spring/config/ProducerConfiguration.java, src/main/resources/application.yml
close #255 
<br>
- kafka 적용
<br>
-
=> [FEAT] kafka 적용

src/main/java/spring/hi_hello_spring/chatting/WebSocketConfig.java, src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java, src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRoom.java, src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatMessageListener.java, src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatRoomService.java, src/main/java/spring/hi_hello_spring/chatting/command/domain/aggregate/ChatMessage.java, src/main/java/spring/hi_hello_spring/chatting/command/domain/repository/mongo/ChatMessageMongoRepository.java, src/main/java/spring/hi_hello_spring/group/command/application/dto/TaskRequestDTO.java
close #261 
<br>
-  roomId 값 겹치는 오류
<br>
-
=> [FIX] roomId 값 겹치는 오류

build.gradle, src/main/java/spring/hi_hello_spring/common/exception/ErrorCodeType.java, src/main/java/spring/hi_hello_spring/wiki/command/application/controller/WikiController.java, src/main/java/spring/hi_hello_spring/wiki/command/application/service/WikiService.java
프론트에서 전달받는 타입 변경으로 인한 위키 등록 기능 리팩토링
close #263
-  위키 등록 기능 리팩토링
=> [REFACTOR] 위키 등록 로직 리팩토링

src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskInputSearchQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskSearchQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskQueryMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java, src/main/resources/mapper/evaluation/task/TaskMapper.xml
[FEAT] 과제 검색 기능 구현
<br>
close #123 
<br>
<br>
- 
<br>
-
=> [FEAT] 과제 검색 기능 구현

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskEvalController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/EvalGroupCreateDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskEvalService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskGroupEvalRepository.java, src/main/java/spring/hi_hello_spring/evaluation/command/infrastructure/JpaTaskGroupEvalRepository.java, src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/PeerReview.java
그룹과제 동료 평가 기능 구현
(+ 로그인 기능 활용해서 테스트 했습니다)
<br>
close #271 
<br>
<br>
- 
<br>
-
=> [FEAT] 그룹과제 동료 평가 기능 구현

src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java, src/main/java/spring/hi_hello_spring/security/filter/CustomAuthenticationFilter.java
close #276 
<br>
<br>
- Spring Security CORS 설정 및 엔드포인트 변경
=> [REFACTOR] Spring Security CORS 설정 및 엔드포인트 변경

src/main/java/spring/hi_hello_spring/common/exception/ErrorCodeType.java, src/main/java/spring/hi_hello_spring/notify/controller/NotifyController.java, src/main/java/spring/hi_hello_spring/notify/dto/NotifyDTO.java, src/main/java/spring/hi_hello_spring/notify/entity/NotiType.java, src/main/java/spring/hi_hello_spring/notify/entity/Notify.java, src/main/java/spring/hi_hello_spring/notify/repository/EmitterRepository.java, src/main/java/spring/hi_hello_spring/notify/repository/EmitterRepositoryImpl.java, src/main/java/spring/hi_hello_spring/notify/repository/NotifyRepository.java, src/main/java/spring/hi_hello_spring/notify/service/NotifyService.java, src/main/java/spring/hi_hello_spring/notify/service/NotifyServiceImpl.java
알림 전송 기능 구현
<br>
close #270 
<br>
<br>
- 알림 전송 기능 구현
<br>
-
=> [FEAT] 알림 전송 기능 구현

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/EvalListCreateDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskUpdateDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/Task.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/service/EvalListDomainService.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/TemplateRepository.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/service/TemplateDomainService.java, src/main/resources/data.sql
과제 수정 기능 구현
<br>
close #275 
<br>
<br>
- 
<br>
-
=> [FEAT] 과제 수정 기능 구현

src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
로그인 엔드 포인트 및 필터 설정 변경
<br>
close #281 
<br>
<br>
- 로그인 엔드포인트 및 필터 설정 변경
<br>
-
=> [CHORE] 로그인 엔드포인트 및 필터 설정 변경

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/Task.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskRepository.java
과제 삭제 기능 구현
<br>
close #280 
<br>
<br>
- 
<br>
-
=> [FEAT] 과제 삭제 기능 구현

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskSubmitDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/Task.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/TaskSubmit.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskRepository.java
과제제출 기능 구현
<br>
close #284 
<br>
<br>
- 
<br>
-
=> [FEAT] 과제제출 기능 구현

src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskSubmitDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/TaskSubmit.java, src/main/resources/data.sql
과제 제출 로직 수정
close #284 
<br>
<br>
- 
<br>
-
=> [CHORE] 과제 제출 로직 수정

src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMenteeDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java, src/main/resources/mapper/evaluation/task/TaskMapper.xml
멘티 본인 과제 상세조회 기능 로직 수정
<br>
close #289 
<br>
<br>
- 
<br>
-
=> [CHORE] 멘티 본인 과제 상세조회 기능 로직 수정

src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMenteeDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMentorDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryService.java, src/main/resources/mapper/evaluation/task/TaskMapper.xml
멘토 멘티 과제 상세조회 기능 로직 수정
close #293 
<br>
<br>
- 
<br>
-
=> [REFACOTR] 멘토 멘티 과제 상세조회 기능 로직 수정

src/main/resources/mapper/evaluation/task/TaskMapper.xml
멘토 과제 리스트 조회 기능 쿼리문 수정
<br>
close #296 
<br>
<br>
- 
<br>
-
=> [CHORE] 멘토 과제 리스트 조회 기능 쿼리문 수정

src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskAllListQueryDTO.java, src/main/resources/mapper/evaluation/task/TaskMapper.xml
담당자 과제 리스트 조회 기능 쿼리문 수정
<br>
close #298 
<br>
<br>
- 
<br>
-
=> [CHORE] 담당자 과제 리스트 조회 기능 쿼리문 수정

src/main/java/spring/hi_hello_spring/chatting/query/controller/ChattingQueryController.java, src/main/java/spring/hi_hello_spring/chatting/query/mapper/ChattingMapper.java, src/main/java/spring/hi_hello_spring/chatting/query/service/ChattingQueryService.java, src/main/resources/mapper/chatting/ChattingListMapper.xml
close #301 
<br>
- type 수정
<br>
-
=> [REFACTOR] type 수정

src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
시큐리티 요청 헤더, 토큰 관련 수정
<br>
close #303 
<br>
<br>
- 시큐리티 요청 헤더, 토큰 관련 수정
<br>
-
=> [CHORE] 시큐리티 요청 헤더, 토큰 관련 수정

src/main/java/spring/hi_hello_spring/wiki/query/dto/WikiListQueryDTO.java, src/main/java/spring/hi_hello_spring/wiki/query/service/WikiQueryService.java, src/main/resources/mapper/wiki/WikiMapper.xml
WikiListQueryDTO 컬럼명 변경
close #305
-  WikiListQueryDTO 컬럼명 변경
=> [REFACTOR] WikiListQueryDTO 컬럼명 변경

src/main/java/spring/hi_hello_spring/common/aggregate/entity/File.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskCreateDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/aggregate/entity/Task.java, src/main/resources/data.sql, src/main/resources/hihellodb.sql
과제 등록 기능 코드 수정
close #300 
<br>
<br>
- 
<br>
-
=> [REFACTOR] 과제 등록 기능 코드 수정

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskUpdateDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
과제 수정 기능 코드 수정
<br>
close #308 
<br>
<br>
- 
<br>
-
=> [REFACTOR] 과제 수정 기능 코드 수정

src/main/java/spring/hi_hello_spring/common/aggregate/entity/File.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskSubmitDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
과제 제출 기능 코드 수정
<br>
close #310 
<br>
<br>
- 
<br>
-
=> [REFACTOR] 과제 제출 기능 코드 수정

src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java
close #312 
<br>
-  mongoDB 저장
<br>
-
=> [REFACTOR] mongoDB 저장

src/main/resources/mapper/wiki/WikiMapper.xml
위키 조회 시 오류 해결
close #314
- 위키 조회 시 오류 해결
=> [FIX] 위키 조회 시 오류 해결

src/main/java/spring/hi_hello_spring/security/service/CustomUserDetailsService.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
시큐리티 엑세스 토큰 생성 과정 수정
<br>
close #316 
<br>
<br>
- 시큐리티 엑세스 토큰 생성 과정 수정
<br>
-
=> [CHORE] 시큐리티 엑세스 토큰 생성 과정 수정

src/main/java/spring/hi_hello_spring/finalEval/query/controller/FinalEvalQueryController.java, src/main/java/spring/hi_hello_spring/finalEval/query/mapper/FinalEvalMapper.java, src/main/java/spring/hi_hello_spring/finalEval/query/service/FinalEvalQueryService.java, src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml, src/main/resources/mapper/finalEval/FinalEvalMapper.xml
최종 평가 목록 검색 기능 구현
close #318
- 최종 평가 목록 검색 기능 구현
=> [FEAT] 최종 평가 목록 검색 기능 구현

docker-compose.yml, src/main/java/spring/hi_hello_spring/chatting/WebSocketConfig.java, src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java, src/main/java/spring/hi_hello_spring/chatting/command/application/dto/ChatRequestMessage.java, src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatMessageListener.java, src/main/java/spring/hi_hello_spring/config/ListenerConfiguration.java, src/main/java/spring/hi_hello_spring/config/SocketTextHandler.java, src/main/resources/application.yml
close #312
<br>
<br>
- kafka topic 수정
<br>
-
=> [REFACTOR] kafka topic 수정

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml
멘토/멘티 프로필 조회 api 분리
<br>
close #321 
<br>
<br>
- 멘토/멘티 프로필 조회 api 분리
<br>
-
=> [CHORE] 멘토/멘티 프로필 조회 api 분리

src/main/java/spring/hi_hello_spring/onboarding/query/controller/OnboardingQueryController.java, src/main/java/spring/hi_hello_spring/onboarding/query/mapper/OnboardingMapper.java, src/main/java/spring/hi_hello_spring/onboarding/query/service/OnboardingQueryService.java, src/main/resources/mapper/onboarding/OnboardingMapper.xml
멘토/멘티 온보딩 리스트 조회 api 분리
<br>
close #323 
<br>
<br>
- 멘토/멘티 온보딩 리스트 조회 api 분리
<br>
-
=> [CHORE] 멘토/멘티 온보딩 리스트 조회 api 분리

src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java
로그인 시 리프레시 토큰 저장 활성화
<br>
close #325 
<br>
<br>
- 로그인 시 리프레시 토큰 저장 활성화
<br>
-
=> [CHORE] 로그인 시 리프레시 토큰 저장 활성화

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java
사원 관련 API 엔드포인트 수정
<br>
close #327 
<br>
<br>
- 사원 관련 API 엔드포인트 수정
<br>
-
=> [CHORE] 사원 관련 API 엔드포인트 수정

src/main/java/spring/hi_hello_spring/mentoring/query/controller/MentoringQueryController.java
close #329 
<br>
<br>
- 한국어 깨짐 오류
<br>
-
=> [FIX] 한국어 깨짐 오류

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
과제 등록 로직 수정
close #333
<br>
<br>
- 
<br>
-
=> [CHORE] 과제 등록 로직 수정

src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizCategoryController.java
close #335
<br>
<br>
- 퀴즈 카테고리 등록 코드 리펙토링
=> [REFACTOR] 퀴즈 카테고리 등록 코드 리펙토링

docker-compose.yml
docker mongodb 버전 수정
close #331 
<br>
<br>
- 
<br>
-
=> [CHORE] docker mongodb 버전 수정

src/main/java/spring/hi_hello_spring/quiz/command/application/controller/QuizController.java
close #339 
<br>
<br>
- @RequestBody 속성 추가 작업
=> [REFACTOR] @RequestBody 속성 추가 작업

src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java, src/main/java/spring/hi_hello_spring/employee/command/domain/repository/DepartmentRepository.java, src/main/java/spring/hi_hello_spring/employee/command/domain/repository/PositionRepository.java, src/main/java/spring/hi_hello_spring/security/entity/CustomUserDetails.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java, src/main/java/spring/hi_hello_spring/security/handler/LoginSuccessHandler.java, src/main/java/spring/hi_hello_spring/security/service/CustomUserDetailsService.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
무한 루프 원인 수정
<br>
close #337 
<br>
<br>
- 무한 루프 원인 수정
<br>
-
=> [FIX] 토큰 검증 과정 무한 루프 원인 수정

src/main/java/spring/hi_hello_spring/mentoring/query/dto/MentoringPlanListAllQueryDTO.java, src/main/resources/mapper/mentoring/MentoringPlanningMapper.xml
close #234 
<br>
<br>
-  planningSeq 추가
<br>
-
=> [REFACTOR] planningSeq 추가

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java
task 로직 수정
<br>
close #343 
<br>
<br>
- 
<br>
-
=> [CHORE] task 로직 수정

src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringPlanController.java
close #347
<br>
<br>
- @RequestBody 추가
<br>
-
=> [REFACTOR] @RequestBody 추가

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringPlanController.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/DepartmentListDTO.java, src/main/resources/mapper/employee/EmployeeMapper.xml
close #349
<br>
<br>
-  부서 조회
<br>
-
=> [FEAT] 부서 조회

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/dto/DepartmentListDTO.java, src/main/java/spring/hi_hello_spring/employee/query/dto/MentorDepQueryDTO.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml
close #351 
<br>
<br>
- 부서별 멘토 조회
<br>
-
=> [FEAT] 부서별 멘토 조회

src/main/java/spring/hi_hello_spring/employee/query/dto/MenteeDepQueryDTO.java, src/main/java/spring/hi_hello_spring/employee/query/dto/MentorDepQueryDTO.java, src/main/resources/mapper/employee/EmployeeMapper.xml
=> [REFACTOR] mentor, seq 변경

src/main/java/spring/hi_hello_spring/security/entity/CustomUserDetails.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
jwt 생성 시 한글이 깨져서 삽입되어 클라이언트에서 디코딩 시 깨진 값 출력
<br>
close #354 
<br>
<br>
- jwt 생성 시 utf-8로 인코딩 하여 토큰에 삽입
<br>
-
=> [REFACTOR] jwt 생성 시 한글값은 utf-8로 인코딩 해서 삽입

src/main/java/spring/hi_hello_spring/finalEval/query/controller/FinalEvalQueryController.java, src/main/java/spring/hi_hello_spring/finalEval/query/dto/FinalEvalDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/finalEval/query/dto/FinalEvalResultQueryDTO.java, src/main/java/spring/hi_hello_spring/finalEval/query/mapper/FinalEvalMapper.java, src/main/java/spring/hi_hello_spring/finalEval/query/service/FinalEvalQueryService.java, src/main/resources/mapper/finalEval/FinalEvalMapper.xml
최종 평가 상세 조회 기능 리팩토링
close #356
- 최종 평가 상세 조회 기능 리팩토링
=> [REFACTOR] 최종 평가 상세 조회 기능 리팩토링

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/dto/ResEmplInfoQueryDTO.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml
내 프로필 조회 기능 리팩토링
<br>
close #361 
<br>
<br>
- 내 프로필 조회 기능 리팩토링
<br>
-
=> [REFACTOR] 내 프로필 조회 기능 리팩토링

src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskEvalQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskEvalMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskEvalQueryService.java, src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml, src/main/resources/mapper/finalEval/FinalEvalMapper.xml
과제 평가 조회 기능 리팩토링
close #363
- 과제 평가 조회 기능 리팩토링
=> [REFACTOR] 과제 평가 조회 기능 리팩토링

src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/CheckListController.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/dto/CheckListUpdateDTO.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/service/CheckListService.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/CheckListStatus.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/CheckListRepository.java, src/main/java/spring/hi_hello_spring/onboarding/command/infrastructure/repository/JpaChecklistRepository.java, src/main/resources/mapper/onboarding/OnboardingMapper.xml
checklist 수행여부 수정 기능 구현
close #365 
<br>
<br>
- 
<br>
- 온보딩 xml 파일 orderby 절 추가
=> [FEAT] checklist 수행여부 수정 기능 구현

src/main/java/spring/hi_hello_spring/group/query/controller/TaskGroupQueryController.java, src/main/java/spring/hi_hello_spring/group/query/service/TaskGroupQueryService.java
close #371
<br>
<br>
- 그룹 과제 별 그룹 리스트 조회 리펙토링
=> [REFACTOR] 그룹 과제 별 그룹 리스트 조회 리펙토링

src/main/resources/mapper/onboarding/OnboardingMapper.xml
온보딩 xml 파일 수정
close #367
<br>
<br>
- 
<br>
-
=> [CHORE] 온보딩 xml 파일 수정

src/main/java/spring/hi_hello_spring/group/command/application/controller/PeerReviewListController.java
close #369
<br>
<br>
- @RequestBody 속성 추가
=> [REFACTOR] @RequestBody 속성 추가

src/main/java/spring/hi_hello_spring/group/query/controller/PeerReviewResultQueryController.java
close #373
<br>
<br>
- 동료 평가 결과 엔드포인트 변경
=> [REFACTOR] 동료 평가 결과 엔드포인트 변경

src/main/java/spring/hi_hello_spring/group/query/dto/PeerReviewResultAllQueryDTO.java, src/main/java/spring/hi_hello_spring/group/query/mapper/PeerReviewResultMapper.java, src/main/java/spring/hi_hello_spring/group/query/service/PeerReviewResultQueryService.java, src/main/resources/mapper/group/PeerReviewResultMapper.xml
close #375
<br>
<br>
- 담당자 동료 평가 결과 상세 조회 리펙토링
=> [REFACTOR] 담당자 동료 평가 결과 상세 조회 리펙토링

src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/CheckListController.java
체크리스트 컨트롤러 수정
<br>
close #378 
<br>
<br>
- 
<br>
-
=> [CHORE] 체크리스트 컨트롤러 수정

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/EvalIndController.java
EvalIndController 로직 수정
close #380 
<br>
<br>
- 
<br>
-
=> [CHORE] EvalIndController 로직 수정

src/main/java/spring/hi_hello_spring/evaluation/query/controller/EvalListQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskEvalQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskSubmitQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/EvalListsQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/SubmittedTaskQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/EvalIndQueryMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/EvalListMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskEvalQueryMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskSubmitQueryMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/EvalIndQueryService.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/EvalListQueryService.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskEvalQueryService.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskSubmitQueryService.java, src/main/resources/mapper/evaluation/evalList/EvalListMapper.xml, src/main/resources/mapper/evaluation/evalind/EvalIndMapper.xml, src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml, src/main/resources/mapper/evaluation/taskSubmit/TaskSubmitMapper.xml
제출된 과제 내용 및 과제 평가 항목 조회
close #358, #360
- 제출된 과제 내용 및 과제 평가 항목 조회
=> [FEAT] 제출된 과제 내용 및 과제 평가 항목 조회

src/main/java/spring/hi_hello_spring/employee/command/application/controller/EmployeeController.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/EmployeeService.java, src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml
사원 검색 기능 리팩토링
<br>
close #383 
<br>
<br>
- 사원 검색 기능 리팩토링
<br>
-
=> [REFACTOR] 사원 검색 기능 리팩토링

src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
jwt 필터 무한 루프 보수
<br>
close #385 
<br>
<br>
- jwt 필터 무한 루프 보수
<br>
-
=> [FIX] jwt 필터 무한 루프 보수

src/main/resources/mapper/employee/EmployeeMapper.xml
사원 목록 조회 쿼리문 수정
<br>
close #390 
<br>
<br>
- 사원 목록 조회 쿼리문 수정
<br>
-
=> [REFACTOR] 사원 목록 조회 쿼리문 수정

src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/TemplateController.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/dto/TemplateCreateDTO.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/dto/TemplateUpdateList.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/service/TemplateService.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/TemplateType.java, src/main/resources/mapper/onboarding/TemplateMapper.xml
close #387
close #388 
<br>
<br>
-  enumtype 수정
-  순서 변경 로직 수정
<br>
-
=> [REFACTOR] enumtype 수정, 순서 변경 로직 수정

src/main/java/spring/hi_hello_spring/common/aggregate/entity/File.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/TemplateController.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/dto/TemplateCreateDTO.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/service/TemplateService.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/Template.java, src/main/resources/data.sql, src/main/resources/hihellodb.sql
close #394 
<br>
<br>
- 온보딩 설계 로직 수정
<br>
-
=> [FEAT] 온보딩 설계 로직 수정

src/main/java/spring/hi_hello_spring/employee/command/application/dto/hr/CreateEmplReqDTO.java, src/main/java/spring/hi_hello_spring/employee/command/application/service/HRService.java
사원 등록 dto 수정
<br>
close #397 
<br>
<br>
- 사원 등록 dto 수정
<br>
-
=> [REFACTOR] 사원 등록 dto 수정

src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMenteeDetailQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskMentorDetailQueryDTO.java, src/main/resources/mapper/evaluation/task/TaskMapper.xml
컬럼명 변경으로 인한 오류 수정
<br>
close #396 
<br>
<br>
- 
<br>
-
=> [CHORE] 컬럼명 변경으로 인한 오류 수정

src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/TemplateController.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/dto/CheckListCreateDTO.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/dto/TemplateCreateDTO.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/service/CheckListService.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/service/TemplateService.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/Checklist.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/CheckListStatusRepository.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/ChecklistRepository.java, src/main/java/spring/hi_hello_spring/onboarding/command/infrastructure/repository/JpaChecklistRepository.java, src/main/java/spring/hi_hello_spring/onboarding/command/infrastructure/repository/JpaChecklistStatusRepository.java
close #400 
<br>
<br>
- 온보딩 설계 구현
<br>
-
=> [FEAT] 온보딩 설계 구현

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/TaskEvalController.java, src/main/java/spring/hi_hello_spring/wiki/query/controller/WikiQueryController.java, src/main/java/spring/hi_hello_spring/wiki/query/mapper/WikiMapper.java, src/main/java/spring/hi_hello_spring/wiki/query/service/WikiQueryService.java, src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml, src/main/resources/mapper/wiki/WikiMapper.xml
특정 버전의 위키 내용 조회 기능 구현
close #402
- 특정 버전의 위키 내용 조회 기능 구현
=> [FEAT] 특정 버전의 위키 내용 조회 기능 구현

src/main/java/spring/hi_hello_spring/wiki/command/application/service/WikiService.java, src/main/resources/mapper/evaluation/taskSubmit/TaskSubmitMapper.xml
현재 로그인한 회원 정보 이용하도록 수정
close #404
- 현재 로그인한 회원 정보 이용하도록 수정
=> [CHORE] 현재 로그인한 회원 정보 이용하도록 수정

src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/ReportListQueryDTO.java, src/main/java/spring/hi_hello_spring/mentoring/query/mapper/ReportMapper.java, src/main/java/spring/hi_hello_spring/mentoring/query/service/ReportQueryService.java, src/main/resources/mapper/mentoring/ReportMapper.xml
팀장, 담당자 검색 기능 구분 구현
<br>
close #407 
<br>
<br>
- 팀장, 담당자 검색 기능 구분 구현
<br>
-
=> [FEAT] 팀장, 담당자 검색 기능 구분 구현

src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/ReportController.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/dto/WriteReportDTO.java, src/main/java/spring/hi_hello_spring/mentoring/query/controller/ReportQueryController.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/MenteeReportListQueryDTO.java
보고서 상세 조회 및 수정 관련 api 리팩토링
<br>
close #411 
<br>
<br>
- 보고서 상세 조회 및 수정 관련 api 리팩토링
<br>
-
=> [REFACTOR] 보고서 상세 조회 및 수정 관련 api 리팩토링

src/main/resources/data.sql
close #414 
<br>
<br>
- data 수정
<br>
-
=> [FIX] data 수정

src/main/java/spring/hi_hello_spring/mentoring/command/application/service/ReportService.java, src/main/java/spring/hi_hello_spring/notify/controller/NotifyController.java, src/main/java/spring/hi_hello_spring/notify/dto/NotifyDTO.java, src/main/java/spring/hi_hello_spring/notify/entity/NotiType.java, src/main/java/spring/hi_hello_spring/notify/service/NotifyServiceImpl.java
멘토링 보고서 작성 시 sse를 통한 실시간 알림 전송 기능 구현
<br>
close #417 
<br>
<br>
- 멘토링 보고서 작성 시 sse를 통한 실시간 알림 전송 기능 구현
<br>
-
=> [FEAT] 멘토링 보고서 작성 시 sse를 통한 실시간 알림 전송 기능 구현

src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
jwtFilter 리팩토링
<br>
close #419 
<br>
<br>
- jwtFilter 리팩토링
<br>
-
=> [FIX] jwtFilter 리팩토링

src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
권한 설정 추가 및 엑세스 토큰 검증 로직 추가
<br>
close #429 
<br>
<br>
- 권한 설정 추가 및 엑세스 토큰 검증 로직 추가
<br>
-
=> [REFACTOR] 권한 설정 추가 및 엑세스 토큰 검증 로직 추가

src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/main/resources/mapper/evaluation/taskSubmit/TaskSubmitMapper.xml
과제 수정 기능 로직 변경
<br>
close #431 
<br>
<br>
- 
<br>
-
=> [CHORE] 과제 수정 기능 로직 변경

src/main/java/spring/hi_hello_spring/employee/query/dto/EmployeeRoleDTO.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/onboarding/query/controller/TemplateQueryController.java, src/main/java/spring/hi_hello_spring/onboarding/query/dto/TemplateTaskRoundDTO.java, src/main/java/spring/hi_hello_spring/onboarding/query/mapper/TemplateMapper.java, src/main/java/spring/hi_hello_spring/onboarding/query/service/TemplateQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml, src/main/resources/mapper/onboarding/TemplateMapper.xml
권한 별 템플릿 차수 조회 기능 구현
<br>
close #433 
<br>
<br>
- 
<br>
-
=> [FEAT] 권한 별 템플릿 차수 조회 기능 구현

src/main/java/spring/hi_hello_spring/onboarding/query/dto/OnboardingDTO.java, src/main/resources/mapper/onboarding/OnboardingMapper.xml
온보딩 리스트 조회 로직 수정
<br>
close #436 
<br>
<br>
- 
<br>
-
=> [CHORE] 온보딩 리스트 조회 로직 수정

src/main/resources/mapper/evaluation/task/TaskMapper.xml, src/main/resources/mapper/onboarding/TemplateMapper.xml
task, template XML 파일 수정
<br>
close #443 
<br>
<br>
- 
<br>
-
=> [CHORE] task, template XML 파일 수정

.github/workflows/deploy.yml
close #446
<br>
<br>
- 엑션즈 코드 수정 작업
=> [REFACTOR] 엑션즈 코드 수정 작업

src/test/java/spring/hi_hello_spring/HiHelloSpringApplicationTests.java
close #449
<br>
<br>
- gradle 빌드 안되는 이슈 해결
=> [REFACTOR] gradle 빌드 안되는 이슈 해결

.github/workflows/deploy.yml
close #451
<br>
<br>
- 배포용 엑션즈 코드 순서 변경 작업
=> [REFACTOR] 배포용 엑션즈 코드 순서 변경 작업

src/main/java/spring/hi_hello_spring/mentoring/command/application/controller/MentoringPlanController.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringPlanService.java, src/main/java/spring/hi_hello_spring/notify/command/domain/aggregate/entity/NotiType.java
팀장이 계획서 처리 시 알림 가도록 리팩토링
<br>
close #453 
<br>
<br>
- 팀장이 계획서 처리 시 알림 가도록 리팩토링
<br>
- 계획서 관련 기능 엔드포인트 수정
=> [REFACTOR] 팀장이 계획서 처리 시 알림 가도록 리팩토링

src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
스웨거 페이지 인증 실패 증상 조치
<br>
close #455 
<br>
<br>
- 권한 설정 수정
<br>
-
=> [FIX] 스웨거 페이지 인증 실패 증상 조치

src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/ChatRoomService.java, src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringPlanService.java, src/main/java/spring/hi_hello_spring/mentoring/command/application/service/ReportService.java, src/main/java/spring/hi_hello_spring/notify/command/application/controller/NotifyController.java, src/main/java/spring/hi_hello_spring/notify/command/application/service/NotifyService.java, src/main/java/spring/hi_hello_spring/notify/command/application/service/NotifyServiceImpl.java
알림 전송 관련 api 리팩토링 및 채팅방 개설 시 알림 전송하도록 리팩토링
<br>
close #459 
<br>
<br>
- 알림 전송 관련 api 리팩토링
- 채팅방 개설 시 알림 전송하도록 리팩토링
<br>
-
=> [REFACTOR] 알림 전송 관련 api 리팩토링 및 채팅방 개설 시 알림 전송하도록 리팩토링

docker-compose.yml, src/main/java/spring/hi_hello_spring/elasticsearch/command/controller/ElasticsearchController.java, src/main/java/spring/hi_hello_spring/elasticsearch/command/document/WikiDocument.java, src/main/java/spring/hi_hello_spring/elasticsearch/command/repository/WikiDocumentRepository.java, src/main/java/spring/hi_hello_spring/elasticsearch/command/service/ElasticsearchService.java, src/main/java/spring/hi_hello_spring/elasticsearch/query/controller/ElasticSearchQueryController.java, src/main/java/spring/hi_hello_spring/elasticsearch/query/service/ElasticsearchQueryService.java, src/main/java/spring/hi_hello_spring/wiki/query/controller/WikiQueryController.java, src/main/java/spring/hi_hello_spring/wiki/query/service/WikiQueryService.java, src/main/resources/application.yml, src/test/java/spring/hi_hello_spring/HiHelloSpringApplicationTests.java
엘라스틱 서치 디렉토리 분리
close #461
- 엘라스틱 서치 디렉토리 분리
=> [REFACTOR] 엘라스틱 서치 디렉토리 분리

src/main/java/spring/hi_hello_spring/mentoring/command/domain/repository/MentoringRepository.java, src/main/java/spring/hi_hello_spring/notify/command/domain/aggregate/entity/NotiType.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/OnboardingStatusController.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/dto/ReqOnboardingStatusDTO.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/service/OnboardingStatusService.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/OnboardingStatus.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/OnboardingStatusRepository.java, src/main/java/spring/hi_hello_spring/onboarding/command/infrastructure/repository/JpaOnboardingStatusRepository.java
(멘티, 멘토) 온보딩 수행 과정 변경 기능 구현 및 알림 전송
<br>
close #465 
<br>
<br>
- (멘티, 멘토) 온보딩 수행 과정 변경 기능 구현 및 알림 전송
<br>
-
=> [FEAT] (멘티, 멘토) 온보딩 수행 과정 변경 기능 구현 및 알림 전송

src/main/java/spring/hi_hello_spring/mentoring/command/application/service/MentoringMatchService.java, src/main/java/spring/hi_hello_spring/notify/command/domain/aggregate/entity/NotiType.java
멘토링 매칭 시 온보디 교육이 시작되며 알림 전송되도록 리팩토링
<br>
close #467 
<br>
<br>
- 멘토링 매칭 시 온보디 교육이 시작되며 알림 전송되도록 리팩토링
<br>
-
=> [REFACTOR] 멘토링 매칭 시 온보디 교육이 시작되며 알림 전송되도록 리팩토링

src/main/java/spring/hi_hello_spring/common/exception/CustomException.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
JwtFilter 검증 실패 시 응답 로직 리팩토링
<br>
close #469 
<br>
<br>
- JwtFilter 검증 실패 시 응답 로직 리팩토링
<br>
-
=> [REFACTOR] JwtFilter 검증 실패 시 응답 로직 리팩토링

src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
토큰 만료시간 수정
<br>
close #471 
<br>
<br>
- 토큰 만료시간 수정
<br>
-
=> [CHORE] 토큰 만료시간 수정

src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/OnboardingStatusController.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/service/OnboardingStatusService.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/OnboardingStatusRepository.java
온보딩 수행상태 변경 api 토글 형식으로 변경
<br>
close #473 
<br>
<br>
- 
<br>
-
=> [REFACTOR] 온보딩 수행상태 변경 api 수정

src/main/java/spring/hi_hello_spring/group/query/controller/TaskGroupQueryController.java, src/main/java/spring/hi_hello_spring/group/query/dto/TaskGroupMembersQueryDTO.java, src/main/java/spring/hi_hello_spring/group/query/mapper/TaskGroupMapper.java, src/main/java/spring/hi_hello_spring/group/query/service/TaskGroupQueryService.java, src/main/resources/mapper/group/TaskGroupMapper.xml
그룹 과제 평가 결과 조회 시 그룹 멤버 조회 API 구현
close #476
- 그룹 과제 평가 결과 조회 시 그룹 멤버 조회 API 구현
=> [FEAT] 그룹 과제 평가 결과 조회 시 그룹 멤버 조회 API 구현

src/main/java/spring/hi_hello_spring/chatting/KafkaConstants.java, src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/KafkaConsumerService.java, src/main/java/spring/hi_hello_spring/config/KafkaConsumerConfig.java, src/main/java/spring/hi_hello_spring/config/KafkaProducerConfig.java, src/main/resources/application.yml
close #475
<br>
<br>
- 카프카 환경 변수 설정 작업
=> [REFACTOR] 카프카 환경 변수 설정 작업

src/main/java/spring/hi_hello_spring/onboarding/query/controller/ChecklistQueryController.java, src/main/java/spring/hi_hello_spring/onboarding/query/mapper/ChecklistMapper.java, src/main/java/spring/hi_hello_spring/onboarding/query/service/ChecklistQueryService.java, src/main/resources/mapper/onboarding/ChecklistMapper.xml
체크리스트 온보딩 수행 여부 변경 관련 API 구현
close #479
- 체크리스트 온보딩 수행 여부 변경 관련 API 구현
=> [FEAT] 체크리스트 온보딩 수행 여부 변경 관련 API 구현

src/main/resources/application.yml
close #481
<br>
<br>
- 
<br>
-
=> [CHORE] 주석 달기

src/main/resources/application.yml
close #{이슈넘버}
<br>
<br>
- 
<br>
-
=> [REFACTOR] 주소 변경

src/main/java/spring/hi_hello_spring/onboarding/command/application/service/OnboardingStatusService.java, src/main/java/spring/hi_hello_spring/onboarding/query/dto/OnboardingDTO.java, src/main/resources/mapper/onboarding/OnboardingMapper.xml
온보딩 데이터 로드 코드 수정
<br>
close #485 
<br>
<br>
- 
<br>
-
=> [REFACTOR] 온보딩 데이터 로드 코드 수정

docker-compose.yml, package-lock.json, src/main/java/spring/hi_hello_spring/chatting/StompHandler.java, src/main/java/spring/hi_hello_spring/chatting/command/application/controller/ChatController.java, src/main/java/spring/hi_hello_spring/chatting/command/application/serivce/KafkaProducerService.java, src/main/java/spring/hi_hello_spring/chatting/query/controller/ChattingQueryController.java, src/main/java/spring/hi_hello_spring/chatting/query/mapper/ChattingMapper.java, src/main/java/spring/hi_hello_spring/chatting/query/service/ChattingQueryService.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java, src/main/resources/mapper/chatting/ChattingListMapper.xml
close #488 
<br>
<br>
- 채팅 관련 수정
<br>
-
=> [REFACTOR] 채팅 관련 수정

src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/CheckListController.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/OnboardingStatusController.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/TemplateController.java
엔드포인트, 변수명 수정
close #490
- 엔드포인트, 변수명 수정
=> [CHORE] 엔드포인트, 변수명 수정

build.gradle, src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java, src/main/resources/application.yml, src/main/resources/data2.sql
프로메테우스 연동 설정 및 data 문 추가
<br>
close #492 
<br>
<br>
- 프로메테우스 연동 설정 및 data 문 추가
<br>
-
=> [FEAT] 프로메테우스 연동 설정 및 data 문 추가

src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/TaskRepository.java, src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java, src/main/java/spring/hi_hello_spring/group/command/domain/repository/TaskGroupRepository.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/controller/TemplateController.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/service/TemplateService.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/TemplateRepository.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java
스케쥴드 기능 구현
<br>
close #487 
<br>
<br>
- 
<br>
-
=> [FEAT] 스케쥴드 기능 구현

src/main/java/spring/hi_hello_spring/evaluation/command/application/controller/EvalListController.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/EvalListService.java, src/main/java/spring/hi_hello_spring/evaluation/command/domain/repository/EvalListRepository.java
평가 항목 제거 기능 구현
<br>
close #497 
<br>
<br>
- 
<br>
-
=> [FEAT] 평가 항목 제거 기능 구현

src/main/java/spring/hi_hello_spring/notify/query/dto/ReadNotifyDTO.java
알림 전송 DTO 리팩토링
<br>
close #499 
<br>
<br>
- 알림 전송 DTO 리팩토링
<br>
-
=> [REFACTOR] 알림 전송 DTO 리팩토링

src/main/java/spring/hi_hello_spring/employee/command/domain/repository/EmployeeRepository.java, src/main/java/spring/hi_hello_spring/onboarding/command/application/service/TemplateService.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/CheckListStatus.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/OnboardingStatus.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/ChecklistRepository.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/repository/OnboardingStatusRepository.java
온보딩 설계 시 온보딩 상태 테이블에 데이터 삽입
close #496 
- 온보딩 설계 시 온보딩 상태 테이블에 데이터 삽입
=> [FEAT] 온보딩 설계 시 온보딩 상태 테이블에 데이터 삽입

src/main/resources/mapper/onboarding/OnboardingMapper.xml
멘티 온보딩 조회 기능 수정
<br>
close #502
<br>
<br>
- 
<br>
-
=> [CHORE] 멘티 온보딩 조회 기능 수정

src/main/resources/mapper/employee/EmployeeMapper.xml
close #504 
<br>
<br>
- 멘토링 매칭 조회 수정
<br>
-
=> [REFACTOR] 멘토링 매칭 조회 수정

src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java
close #506 
<br>
<br>
- 채팅 관련 시큐리티
<br>
-
=> [REFACTOR] 채팅 관련 시큐리티

src/main/resources/data2.sql
data 수정
close #508 
<br>
<br>
- 
<br>
-
=> [CHORE] data 수정

src/main/java/spring/hi_hello_spring/evaluation/query/dto/TaskEvalListQueryDTO.java, src/main/resources/mapper/evaluation/taskEval/TaskEvalMapper.xml
과제 조회 시 데이터에 taskType도 전달
close #511
- 과제 조회 시 데이터에 taskType도 전달
=> [REFACTOR] 과제 조회 시 데이터에 taskType도 전달

src/main/resources/mapper/onboarding/TemplateMapper.xml
쿼리문 수정
<br>
close #515 
<br>
<br>
- 
<br>
-
=> [CHORE] 쿼리문 수정

src/main/resources/data2.sql, src/main/resources/mapper/onboarding/TemplateMapper.xml
close #517
<br>
<br>
- 주차 조회 수정, data.sql 수정
<br>
-
=> [FIX] 주차 조회 수정, data.sql 수정

src/main/java/spring/hi_hello_spring/employee/query/controller/EmployeeQueryController.java, src/main/java/spring/hi_hello_spring/employee/query/mapper/EmployeeMapper.java, src/main/java/spring/hi_hello_spring/employee/query/service/EmployeeQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml
close #519
<br>
<br>
- 매칭이 된 멘티, 전체 멘티 조회 분리
<br>
-
=> [REFACTOR] 매칭이 된 멘티, 전체 멘티 조회 분리

src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/CheckListStatus.java, src/main/java/spring/hi_hello_spring/onboarding/command/domain/aggregate/entity/OnboardingStatus.java
GenerateType AUTO -> IDENTITY
close #522
- GenerateType AUTO -> IDENTITY
=> [REFACTOR] GenerateType AUTO -> IDENTITY

src/main/java/spring/hi_hello_spring/onboarding/command/application/service/CheckListService.java
checklist service문 수정
<br>
close #524 
<br>
<br>
- 
<br>
-
=> [FIX] checklist service문 수정

src/main/java/spring/hi_hello_spring/employee/query/dto/ResEmplInfoQueryDTO.java, src/main/java/spring/hi_hello_spring/onboarding/query/controller/ChecklistQueryController.java, src/main/java/spring/hi_hello_spring/onboarding/query/mapper/ChecklistMapper.java, src/main/java/spring/hi_hello_spring/onboarding/query/service/ChecklistQueryService.java, src/main/resources/mapper/employee/EmployeeMapper.xml, src/main/resources/mapper/onboarding/ChecklistMapper.xml
체크리스트 모두 체크 시 온보딩 수행 상태 변경 오류 해결
close #528
- 체크리스트 모두 체크 시 온보딩 수행 상태 변경 오류 해결
=> [FIX] 체크리스트 모두 체크 시 온보딩 수행 상태 변경 오류 해결

src/main/java/spring/hi_hello_spring/evaluation/command/application/dto/TaskCreateDTO.java, src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/main/java/spring/hi_hello_spring/group/command/application/controller/GroupMatchController.java, src/main/java/spring/hi_hello_spring/group/command/application/service/GroupMatchService.java, src/main/java/spring/hi_hello_spring/group/command/domain/aggregate/entity/TaskGroup.java
close #530
<br>
<br>
- 온보딩 과제 등록 로직 수정
<br>
-
=> [REFACTOR] 온보딩 과제 등록 로직 수정

src/main/java/spring/hi_hello_spring/common/s3/FileUploadUtil.java
S3 로직 수정
<br>
close #521
<br>
<br>
- 
<br>
-
=> [FIX] S3 로직 수정

src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/main/java/spring/hi_hello_spring/evaluation/query/controller/TaskSubmitQueryController.java, src/main/java/spring/hi_hello_spring/evaluation/query/dto/SubmittedTaskQueryDTO.java, src/main/java/spring/hi_hello_spring/evaluation/query/mapper/TaskSubmitQueryMapper.java, src/main/java/spring/hi_hello_spring/evaluation/query/service/TaskSubmitQueryService.java, src/main/java/spring/hi_hello_spring/mentoring/query/dto/MenteeQueryDTO.java, src/main/java/spring/hi_hello_spring/onboarding/query/mapper/OnboardingMapper.java, src/main/java/spring/hi_hello_spring/onboarding/query/service/OnboardingQueryService.java, src/main/resources/mapper/evaluation/taskSubmit/TaskSubmitMapper.xml, src/main/resources/mapper/onboarding/OnboardingMapper.xml
Task 기능 로직 수정
<br>
close #533 
<br>
<br>
- 
<br>
-
=> [FIX] Task 기능 로직 수정

src/main/java/spring/hi_hello_spring/notify/query/controller/NotifyQueryController.java, src/main/java/spring/hi_hello_spring/notify/query/dto/AlarmCountDTO.java, src/main/java/spring/hi_hello_spring/notify/query/mapper/NotifyMapper.java, src/main/java/spring/hi_hello_spring/notify/query/service/NotifyQueryService.java, src/main/resources/mapper/notify/NotifyMapper.xml
읽지 않은 알림 개수 조회 기능 구현
close #{이슈넘버}
<br>
<br>
- 읽지 않은 알림 개수 조회 기능 구현
<br>
-
=> [FEAT] 읽지 않은 알림 개수 조회 기능 구현

src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/test/java/spring/hi_hello_spring/evaluation/command/application/service/TaskEvalServiceTest.java, src/test/java/spring/hi_hello_spring/evaluation/command/application/service/TaskServiceTest.java, src/test/java/spring/hi_hello_spring/evaluation/query/service/TaskQueryServiceTest.java, src/test/java/spring/hi_hello_spring/onboarding/command/application/service/CheckListServiceTest.java
Task, Onboarding 부분 테스트 코드 작성
<br>
close #535 
<br>
<br>
- 
<br>
-
=> [TEST] Task, Onboarding 기능 테스트 코드 작성

src/main/java/spring/hi_hello_spring/security/config/SecurityConfig.java, src/main/java/spring/hi_hello_spring/security/config/SecurityProperties.java, src/main/java/spring/hi_hello_spring/security/filter/JwtFilter.java, src/main/java/spring/hi_hello_spring/security/handler/JwtAccessDeniedHandler.java, src/main/java/spring/hi_hello_spring/security/service/CustomUserDetailsService.java, src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
Security 리팩토링
<br>
close #541 
<br>
<br>
- Security 리팩토링
<br>
-
=> [REFACTOR] Security 리팩토링

src/main/resources/application.yml
close #543
<br>
<br>
- 엘라스틱 서치 활성화
=> [REFACOTR] 엘라스틱 서치 활성화

.github/workflows/deploy.yml
close #546 
<br>
<br>
- deploy 코드 수정
=> [REFACTOR] deploy 코드 수정

src/main/java/spring/hi_hello_spring/config/ElasticsearchIndexInitializer.java, src/main/java/spring/hi_hello_spring/elasticsearch/command/controller/ElasticsearchController.java, src/main/java/spring/hi_hello_spring/elasticsearch/query/service/ElasticsearchQueryService.java
close #551
<br>
<br>
- 
<br>
-
=> [CHORE] 엘라스틱 서치 로그 코드 추가

src/main/java/spring/hi_hello_spring/security/util/JwtUtil.java
엑세스 토큰 만료시간 설정
<br>
close #554 
<br>
<br>
- 엑세스 토큰 만료시간 설정
<br>
-
=> [CHORE] 엑세스 토큰 만료시간 설정

src/main/java/spring/hi_hello_spring/evaluation/command/application/service/TaskService.java, src/main/resources/mapper/evaluation/task/TaskMapper.xml, src/test/java/spring/hi_hello_spring/evaluation/command/application/service/TaskServiceTest.java
과제 등록, 조회 버그 수정
close #556 
<br>
<br>
- 
<br>
-
=> [FIX] 과제 등록, 조회 버그 수정

src/main/java/spring/hi_hello_spring/employee/query/dto/MenteeAllQueryDTO.java, src/main/resources/mapper/employee/EmployeeMapper.xml
=> [REFACTOR] 과제 그룹 매핑 수정

.github/workflows/deploy.yml
close #560
<br>
<br>
- 
<br>
-
=> [REFACTOR] 배포 환경 테스트

.github/workflows/develop.yml
close #563 
<br>
<br>
- 
<br>
-
=> [CHORE] 공백 추가
